name: veno-cert-dev

services:
 mysql: # Nom du service MySQL
  image: mysql:8
  restart: always
  environment:
   MYSQL_DATABASE: "veinoCert"
   MYSQL_USER: "veinoCert"
   MYSQL_PASSWORD: "veinoCert"
   MYSQL_ROOT_PASSWORD: "root"
  ports:
   - "3306:3306"
  volumes:
   - v-mysql-dev:/mysql
  networks:
   - mynetwork

 app:
  build:
   context: ./app
   dockerfile: ./Dockerfile
  ports:
   - "3000:3000"
  environment:
   SERVER_PORT: 3000
   DATABASE_URL: mysql://root:root@mysql:3306/veinoCert
  depends_on:
   - seed
  volumes:
   - v-app-dev:/app
  networks:
   - mynetwork

 seed:
  restart: no
  build:
   context: ./app
   dockerfile: ./migrate.Dockerfile
  environment:
   DATABASE_URL: mysql://root:root@mysql:3306/veinoCert
  depends_on:
   - mysql
  networks:
   - mynetwork

volumes:
 v-mysql-dev:
 v-app-dev:

networks:
 mynetwork:
  driver: bridge
