name: veno-cert-prod

services:
 mysql:
  image: mysql
  restart: always
  environment:
   MYSQL_DATABASE: "veinoCert"
   MYSQL_USER: "veinoCert"
   MYSQL_PASSWORD: "veinoCert"
   MYSQL_ROOT_PASSWORD: "root"
  volumes:
   - v-mysql:/mysql
  networks:
   - mynetwork

 app:
  build:
   context: ./app
   dockerfile: ./Dockerfile
  restart: always
  environment:
   SERVER_PORT: 3000
   DATABASE_URL: mysql://root:root@mysql:3306/veinoCert
  depends_on:
   - seed
   - mysql
  volumes:
   - v-app:/app
  networks:
   - mynetwork

 seed:
  restart: no
  build:
   context: ./app
   dockerfile: ./migrate.Dockerfile
  environment:
   DATABASE_URL: mysql://root:root@mysql:3306/veinoCert
  depends_on:
   - mysql
  networks:
   - mynetwork

 nginx:
  restart: always
  build:
   context: ./nginx
   dockerfile: ./Dockerfile
  ports:
   - 80:80
   - 443:443
  volumes:
   - v-nginx:/nginx
  networks:
   - mynetwork

volumes:
 v-mysql:
 v-nginx:
 v-app:

networks:
 mynetwork:
  driver: bridge
