services:
 mysql: # Nom du service MySQL
  image: mysql:8
  restart: always
  environment:
   MYSQL_DATABASE: "veinoCert"
   MYSQL_USER: "veinoCert"
   MYSQL_PASSWORD: "veinoCert"
   MYSQL_ROOT_PASSWORD: "root"
  ports:
   - "3306:3306"
  networks:
   - mynetwork

 app:
  build: .
  ports:
   - "3000:3000"
  environment:
   SERVER_PORT: 3000
   DATABASE_URL: mysql://root:root@mysql:3306/veinoCert
  depends_on:
   - mysql
  networks:
   - mynetwork

networks:
 mynetwork:
